{% for storageclassname in storageclassname.name() %}
  {{- if storageclassname.create -}}
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    name: {{ storageclassname }}
  {{- if storageclassname.annotations }}
    annotations:
  {{ toYaml storageclassname.annotations | indent 4 }}
  {{- end }}
    labels:
      app: {{ include "ceph-csi-cephfs.name" . }}
      chart: {{ include "ceph-csi-cephfs.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      {{- with .Values.commonLabels }}{{ toYaml . | trim | nindent 4 }}{{- end }}
  provisioner: {{ .Values.driverName }}
  parameters:
    clusterID: {{ storageclassname.clusterID }}
    fsName: {{ storageclassname.fsName }}
  {{- if storageclassname.pool }}
    pool: {{ storageclassname.pool }}
  {{- end }}
  {{- if storageclassname.fuseMountOptions }}
    fuseMountOptions: "{{ storageclassname.fuseMountOptions }}"
  {{- end }}
  {{- if storageclassname.kernelMountOptions }}
    kernelMountOptions: "{{ storageclassname.kernelMountOptions }}"
  {{- end }}
  {{- if storageclassname.mounter }}
    mounter: "{{ storageclassname.mounter }}"
  {{- end }}
  {{- if storageclassname.volumeNamePrefix }}
    volumeNamePrefix: "{{ storageclassname.volumeNamePrefix }}"
  {{- end }}
    csi.storage.k8s.io/provisioner-secret-name: {{ storageclassname.provisionerSecret }}
  {{- if storageclassname.provisionerSecretNamespace }}
    csi.storage.k8s.io/provisioner-secret-namespace: {{ storageclassname.provisionerSecretNamespace }}
  {{ else }}
    csi.storage.k8s.io/provisioner-secret-namespace: {{ .Release.Namespace }}
  {{- end }}
    csi.storage.k8s.io/controller-expand-secret-name: {{ storageclassname.controllerExpandSecret }}
  {{- if storageclassname.controllerExpandSecretNamespace }}
    csi.storage.k8s.io/controller-expand-secret-namespace: {{ storageclassname.controllerExpandSecretNamespace }}
  {{ else }}
    csi.storage.k8s.io/controller-expand-secret-namespace: {{ .Release.Namespace }}
  {{- end }}
    csi.storage.k8s.io/node-stage-secret-name: {{ storageclassname.nodeStageSecret }}
  {{- if storageclassname.nodeStageSecretNamespace }}
    csi.storage.k8s.io/node-stage-secret-namespace: {{ storageclassname.nodeStageSecretNamespace }}
  {{ else }}
    csi.storage.k8s.io/node-stage-secret-namespace: {{ .Release.Namespace }}
  {{- end }}
  reclaimPolicy: {{ storageclassname.reclaimPolicy }}
  allowVolumeExpansion: {{ storageclassname.allowVolumeExpansion }}
  {{- if storageclassname.mountOptions }}
  mountOptions:
    {{- range storageclassname.mountOptions }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- end -}}
{% endfor -%}
